apiVersion: v1
kind: Service
metadata:
  name: service-inshine-database
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
      name: inshine-database
      app: inshine-database

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inshine-database
spec:
  replicas: 1
  serviceName: inshine-database
  selector:
    matchLabels:      
        name: inshine-database
        app: inshine-database 
  template:
    metadata:
      name: inshine-database-mysql
      labels:
        name: inshine-database
        app: inshine-database
    spec:
      # terminationGracePeriodSeconds: 10
      containers:
        - name: inshine-database
          image: atulpatil22/inshine-database

          env:
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mysql-config-map
                key: DB_NAME

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: DB_PASSWORD

  volumeClaimTemplates:
  - metadata:
      name: inshine-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi


