
apiVersion: v1
kind: Service
metadata:
  name: service-inshine
spec:
  clusterIP: None
  selector:
      name: inshine-backend
      app: inshine-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-inshine-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: inshine-backend
      app: inshine-backend
    
  template:
    metadata:
      name: inshine-backend
      labels:
        name: inshine-backend
        app: inshine-backend
    spec:
      containers:
        - name: inshine-backend
          image: atulpatil22/backend-kube1

          ports:
            - containerPort: 8081

          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-config-map
                key: DB_HOST

          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mysql-config-map
                key: DB_NAME

          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mysql-config-map
                key: DB_USERNAME

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: DB_PASSWORD