
backend:
  image: "atulpatil22/inshine_backend_springboot:latest"
  replicas: 1
      
  metadata_name: development-inshine-
  
  matchLabels:
  
    defaultvalue: inshine-
  
  env:
    host_name: inshine-database
    db_name: inshine
    db_username: root
    db_password: root
  
database:
  image: "atulpatil22/inshine_database_mysql:latest"
  
frontend:
  image: "atulpatil22/inshine_frontend_react:latest"
  
  

