    pipeline {
    
    agent any 
        
    stages {
        
       stage('Build and Push Docker Image') {
         environment {
           DOCKER_IMAGE = "atulpatil22/inshine_backend_jenkins:${BUILD_NUMBER}"    
           REGISTRY_CREDENTIALS = credentials('docker-cred')
        }
         steps {
           script {
               sh '''
                 docker build -t ${DOCKER_IMAGE} 'Inshine/Backend - Inshine/'
                 docker login -u atulpatil22 -p ${REGISTRY_CREDENTIALS}
                 docker push ${DOCKER_IMAGE}
                 '''

              }
           } 
       }
               
     stage('Update Deployment File') {
        environment {
            GIT_REPO_NAME = "kubernetes"
            GIT_USER_NAME = "atulpatil22494"
        }
        steps {
            withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                sh ''' 
                    git config user.email "atul.patil@xenonstack.com"
                    git config user.name "atulpatil22494"
                    BUILD_NUMBER=${BUILD_NUMBER}
                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" yaml_kubernetes/Inshine-backend.yaml
                    git add yaml_kubernetes/Inshine-backend.yaml
                    git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                '''
             }
          }       
       }           
    }
}

       
