    pipeline {
    
    agent any 
        
    stages {
        
       stage('Build and Push Docker Image') {
         environment {
           DOCKER_IMAGE = "atulpatil22/inshine_frontend_jenkins:${BUILD_NUMBER}"    
           REGISTRY_CREDENTIALS = credentials('docker-cred')
        }
         steps {
           script {
               sh '''
                 docker build -t ${DOCKER_IMAGE} 'Inshine/Frontend - Inshine/reactt'
                 docker login -u atulpatil22 -p ${REGISTRY_CREDENTIALS}
                 docker push ${DOCKER_IMAGE}
                 '''

              }
           }
         }
      }
   }

       
