apiVersion: batch/v1
kind: CronJob
metadata: 
  name: cronjob-demo
spec: 
  schedule: "*/1 * * * *"
  jobTemplate:
    spec: 
      activeDeadlineSeconds: 17
      template:
        spec: 
          containers: 
            - name: busybox-container
              image: busybox
              command: 
                - /bin/sh
                - -c
                - "date; echo hello from kubernetes cluster"
          restartPolicy: OnFailure


# Check the logs of the job to see the result
# kubectl logs jobs/cronjob-demo-<job-speci>