apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: busybox-init
    image: busybox
    command: ["wget", "-O", "/work-dir/index.html", "http://neverssl.com/online"]
    volumeMounts:
    - name: shared-data
      mountPath: /work-dir
  volumes:
  - name: shared-data
    emptyDir: {}


# Get the IP of the nginx-busybox-pod
# pod_ip=$(kubectl get pod nginx-busybox-pod -o=jsonpath='{.status.podIP}')

# Create a busybox pod and run wget to fetch the content from the nginx-busybox-pod
# kubectl run busybox-pod --image=busybox --restart=Never -- wget -O- $pod_ip