apiVersion: batch/v1
kind: Job
metadata:
  name: calculate-pi-job
spec:
  template:
    spec:
      containers:
      - name: perl-container
        image: perl
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4  # The number of retries in case of failure


  # Check the logs of the job to see the result
# kubectl logs jobs/calculate-pi-job

# Export the result to a file named pi-result.txt
# kubectl logs calculate-pi-job > pi-result.txt