apiVersion: v1
kind: Pod
metadata: 
  name: red
spec: 
  containers: 
    - name: nginx-container
      image: nginx
  initContainers:
    - name: busybox-init
      image: busybox
      command: ["sleep" , "20"] 