apiVersion: v1
kind: Pod
metadata: 
  name: two-container-pod
spec: 
  containers:
    - name: container1
      image: busybox
      command: ["sh", '-c', "echo hello; sleep 3600"]
    - name: container2
      image: busybox
      command: ["sh", "-c", "sleep 3600"]


# Connect to the second container in the pod
# kubectl exec -it $pod_name -c container2 -- sh