apiVersion: v1
kind: Pod
metadata:
  name: nginx03
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30  # Delay the probe for the initial warm-up period of nginx server.
        periodSeconds: 10         # Check the readiness every 10 seconds