apiVersion: v1
kind: Pod
metadata:
  name: box0
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 30; touch /tmp/debug; sleep 30; rm /tmp/debug"]
      readinessProbe:
        exec:
          command:
            - sh
            - -c
            - "[ -f /tmp/debug ]"
        initialDelaySeconds: 5
        periodSeconds: 5