apiVersion: v1
kind: Service
metadata:
  name: service-inshine-backend
spec:
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30092
  selector:
        name: inshine-backend
        app: inshine-backend
  type: NodePort