apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-inshine-database
spec:
  replicas: 1
  selector:
    matchLabels:      
        name: inshine-database
        app: inshine-database    
  template:
    metadata:
      name: inshine-database-mysql
      labels:
        name: inshine-database
        app: inshine-database
    spec:
      containers:
        - name: inshine-database
          image: atulpatil22/inshine-database
          # env:
          #   - name: DB_PASSWORD
          #     value: "root"
          #   - name: DB_NAME
          #     value: "inshine"
          env:
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mysql-config-map
                key: DB_NAME

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: DB_PASSWORD

          ports:
            - containerPort: 3306
              name: mysql

          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistance-storage
      volumes:
        - name: mysql-persistance-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim